AllCops:
  Exclude:
    - tmp/**/*
    - vendor/**/*
    - test/fixtures/**/*
    - test/functions.rb

Layout/AlignHash:
  EnforcedHashRocketStyle: table
  EnforcedColonStyle: table

Metrics/BlockLength:
  Exclude:
    - spec/**/*
    - licensee.gemspec

Style/Documentation:
  Enabled: false

Layout/EndAlignment:
  EnforcedStyleAlignWith: variable
  AutoCorrect: true

Metrics/MethodLength:
  Enabled: false

Metrics/ClassLength:
  Enabled: false

Metrics/ModuleLength:
  Enabled: false

Metrics/AbcSize:
  Enabled: false

Layout/IndentHeredoc:
  Enabled: false

Style/StructInheritance:
  Enabled: false

Metrics/LineLength:
  Exclude:
    - bin/*
    - lib/licensee/commands/*

Metrics/PerceivedComplexity:
  Exclude:
    - lib/licensee/commands/*

Metrics/CyclomaticComplexity:
  Exclude:
    - lib/licensee/commands/*
