#!/usr/bin/env ruby
# frozen_string_literal: true

require 'json'
require 'licensee'

options = { detect_packages: true, detect_readme: true }
project = Licensee::Projects::FSProject.new('.', **options)
json = JSON.pretty_generate(project.to_h)
File.write('./spec/fixtures/detect.json', json)
