#!/usr/bin/env ruby

require_relative '../spec/spec_helper.rb'

fixtures_licenses = {}
options = { detect_packages: true, detect_readme: true }
fixtures.each do |fixture|
  path = fixture_path(fixture)
  project = Licensee.project(path, options)

  fixtures_licenses[fixture] = { "key" => nil, "matcher" => nil, "hash" => nil }

  fixtures_licenses[fixture]["key"] = project.license&.key
  fixtures_licenses[fixture]["hash"] = project.license_file&.content_hash

  matcher = project.license_file&.matcher&.name
  fixtures_licenses[fixture]["matcher"] = matcher.to_s if matcher
end

output = "# Map of fixtures to expectation as an added integration test\n"
output << YAML.dump(fixtures_licenses)
File.write fixture_path('fixtures.yml'), output
