#!/usr/bin/env ruby

require_relative '../spec/spec_helper.rb'

fixtures_licenses = {}
options = { detect_packages: true, detect_readme: true }
fixtures.each do |fixture|
  path = fixture_path(fixture)
  project = Licensee.project(path, options)
  fixtures_licenses[fixture] = project.license ? project.license.key : nil
end

output = "# Map of fixtures to expected licenses as an added integration test\n"
output << YAML.dump(fixtures_licenses)
File.write fixture_path('fixtures-license.yml'), output
