#!/bin/sh
# Runs the licensee command against a remote git repo

repo=$1
name=$(basename $repo)
dir="./tmp/$name"

git clone --depth 1 --quiet "$repo" "$dir"
bundle exec bin/licensee "$dir"

rm -Rf "$dir"
