#!/bin/sh
# Bump, tag, and push a release
# Usage script/release minor

set -e

if [[ -z $1 ]] ; then
  echo 'Must provide a release type (e.g., minor). See https://github.com/svenfuchs/gem-release#description-1'
  exit 1
fi

bundle exec gem bump --version $1 --tag --release --push
