#!/bin/sh

#rm -Rf vendor/choosealicense.com
#bower install github/choosealicense.com#gh-pages

rm -Rf vendor/spdx-license-list
mkdir -p vendor/spdx-license-list/template
wget https://github.com/spdx/license-list-data/archive/master.zip -O tmp.zip
unzip -j tmp.zip *.txt -d vendor/spdx-license-list/template
rm tmp.zip
bundle exec script/prune-spdx-templates
