#!/bin/sh

VENDOR_DIR=vendor/choosealicense.com
rm -rf "$VENDOR_DIR"
mkdir -p "$VENDOR_DIR"

case "$(tar --version 2>/dev/null | sed -n '1p')" in
  *bsdtar*)
    set --
    ;;
  *)
    set -- --wildcards --no-wildcards-match-slash
    ;;
esac

curl -L https://api.github.com/repos/github/choosealicense.com/tarball |
  tar zxf - -C "$VENDOR_DIR" "$@" --strip-components=1 \
    '*/_data/*.yml' \
    '*/_licenses/*'
