name: Docker

on:
  push:
    branches: [main]
    paths:
      - Dockerfile
      - .github/workflows/docker.yml
  pull_request:
    branches: [main]
    paths:
      - Dockerfile
      - .github/workflows/docker.yml

permissions:
  contents: read

jobs:
  build-image:
    runs-on: ubuntu-latest

    steps:
      - name: Harden Runner
        uses: step-security/harden-runner@bf7454d06d71f1098171f2acdf0cd4708d7b5920 # v2.20.0
        with:
          egress-policy: audit

      - name: Checkout
        uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0

      - name: Build docker images
        run: docker build . --tag licensee

      - name: Smoke test
        run: docker run licensee