name: Docker

on:
  push:
    branches: [main]
    paths:
      - Dockerfile
      - .github/workflows/docker.yml
  pull_request:
    branches: [main]
    paths:
      - Dockerfile
      - .github/workflows/docker.yml

permissions:
  contents: read

jobs:
  build-image:
    runs-on: ubuntu-latest

    steps:
      - name: Harden Runner
        uses: step-security/harden-runner@e14015d583714f6e62063499dc959a02595150a1 # v2.21.1
        with:
          egress-policy: audit

      - name: Checkout
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1

      - name: Build docker images
        run: docker build . --tag licensee

      - name: Smoke test
        run: docker run licensee